apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: eytb65epc-python 
  janus-idp.io/tekton: eytb65epc-python
  backstage.io/kubernetes-id: eytb65epc-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: eytb65epc-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  