apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: eytb65epc-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: eytb65epc-python 
  name: eytb65epc-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: eytb65epc-python 
